[theme]
primaryColor = "#ffc107"
backgroundColor = "#3b3737ff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#333333ff"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"