[theme]
primaryColor = "#ffc107"
backgroundColor = "#e8f1f8"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#333"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"